version: '3'
services:
  expresscart:
    build: .
    container_name: "expresscart"
    environment:
      NODE_ENV: production
      NODE_PATH: /
    ports:
      - "1111:1111"
    volumes:
      - uploads:/var/expressCart/public/uploads

  expresscart-dev:
    image: "node:16.13.0"
    container_name: "expresscart-dev"
    profiles: ["development"]
    environment:
      NODE_ENV: development
      NODE_PATH: /
      databaseConnectionString : mongodb://expresscart-mongodb:27017/expresscart
    ports:
      - "1111:1111"
    volumes:
      - uploads:/var/expressCart/public/uploads
    links:
      - mongodb
    depends_on:
      - mongodb

  testdata:
    image: "node:16"
    profiles: ["testdata"]
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    environment:
      NODE_ENV: development
      NODE_PATH: /
      databaseConnectionString: mongodb://expresscart-mongodb:27017/expresscart
    command: npm run testdata
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    profiles: ["development"]
    container_name: "expresscart-mongodb"
    volumes:
      - expresscart-mongo-data:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
volumes:
  expresscart-mongo-data:
  uploads:
