apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}expresscart
  labels:
    app: {{ .Release.Name }}-expresscart
    name: {{ .Release.Name }}-expresscart
     {{- template "labels" . }}
spec:
  replicas: {{ .Values.expresscart.replicaCount }}
  template:
    metadata:
      annotations:
        name: {{ .Release.Name }}-expresscart
        author: test
      labels:
        app: {{ .Release.Name }}-expresscart
        env: dev
    spec:
      containers:
      - name: expresscart
        image: {{ .Values.expresscart.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "http"
        links:
        - mongodb
        depends_on:
        - mongodb
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.expresscart.env }}
          path: /
